Fix #23: multiple options can be used without space.

diff --git a/bin/xpanes b/bin/xpanes
--- a/bin/xpanes
+++ b/bin/xpanes
@@ -30,6 +30,10 @@ readonly _XP_CACHE_HOME="${XDG_CACHE_HOME}/xpanes"
 # __xpanes::main
 : "Initialize options" && {
     _XP_OPTIONS=()
+    # options which work indivisually.
+    _XP_FLAG_OPTIONS="[hVld]"
+    # options which requre arguments.
+    _XP_FREE_OPTIONS="[ISc]"
     _XP_ARGS=()
     _XP_STDIN=()
     _XP_OPT_IS_SYNC=1
@@ -438,6 +442,113 @@ __xpanes::switch_xargs_mode() {
     _XP_ARGS=("${_XP_STDIN[@]}")
 }
 
+__xpanes::load_flag_options() {
+    if   [[ "$1" =~ h ]]; then
+        __xpanes::usage
+        __xpanes::usage_verbose
+        exit 0
+    fi
+    if [[ "$1" =~ V ]]; then
+        __xpanes::version
+        exit 0
+    fi
+    if [[ "$1" =~ l ]]; then
+        _XP_OPT_LOG_STORE=1
+    fi
+    if [[ "$1" =~ d ]]; then
+        _XP_OPT_IS_SYNC=0
+    fi
+    return 1
+}
+
+__xpanes::load_free_options() {
+    # Extract flag options only.
+    __xpanes::load_flag_options "$(echo "$1" | perl -nle "/^-$_XP_FLAG_OPTIONS+/ and $&")" > /dev/null
+    if [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}*I ]]; then
+        if [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}*I.+ ]]; then
+            _XP_REPSTR="$(echo "$1" | perl -ple "s/^-${_XP_FLAG_OPTIONS}*?I//")"
+            return 1
+        # Behavior like this.
+        # -IAAA         -- _XP_REPSTR="AAA"
+        # -I AAA BBB    -- _XP_REPSTR="AAA"
+        # -I"AAA BBB"   -- _XP_REPSTR="AAA BBB"
+        # -IAAA BBB     -- _XP_REPSTR="AAA", _XP_ARGS=("BBB")
+        # -I -d ...     -- _XP_REPSTR="{}"
+        elif ! [[ "$2" =~ ^-.* ]]; then
+            _XP_REPSTR="$2"
+            return 2
+        fi
+    elif [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}*c ]]; then
+        if [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}*c.+ ]]; then
+            _XP_CMD_UTILITY="$(echo "$1" | perl -ple "s/^-${_XP_FLAG_OPTIONS}*?c//")"
+            return 1
+        elif ! [[ "$2" =~ ^-.* ]]; then
+            _XP_CMD_UTILITY="$2"
+            return 2
+        fi
+    elif [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}*S ]]; then
+        if [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}*S.+ ]]; then
+            _XP_SOCKET_PATH="$(echo "$1" | perl -ple "s/^-${_XP_FLAG_OPTIONS}*?S//")"
+            return 1
+        elif ! [[ "$2" =~ ^-.* ]]; then
+            _XP_SOCKET_PATH="$2"
+            return 2
+        fi
+    fi
+    return 0
+}
+
+__xpanes::enable_long_options() {
+    if   [[ "$1" =~ ^--help$ ]]; then
+        __xpanes::usage
+        __xpanes::usage_verbose
+        exit 0
+    elif [[ "$1" =~ ^--version$ ]]; then
+        __xpanes::version
+        exit 0
+    elif [[ "$1" =~ ^--desync$ ]]; then
+        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
+        _XP_OPT_IS_SYNC=0
+        return 1
+    elif [[ "$1" =~ ^--log-format=.*$ ]]; then
+        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
+        _XP_OPT_LOG_STORE=1
+        _XP_LOG_FORMAT="${1#--log-format=}"
+        return 1
+    elif [[ "$1" =~ ^--log ]]; then
+        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
+        _XP_OPT_LOG_STORE=1
+        if [[ "$1" =~ ^--log=.*$  ]]; then
+            _XP_LOG_DIR="${1#--log=}"
+        fi
+        return 1
+    elif [[ "$1" =~ ^--ssh$ ]]; then
+        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
+        _XP_CMD_UTILITY="$_XP_SSH_CMD_UTILITY"
+        return 1
+        # For unit testing
+    elif [[ "$1" =~ ^--dry-run$ ]]; then
+        _XP_OPT_DRY_RUN=1
+        return 1
+    elif [[ "$1" =~ ^--kill$ ]]; then
+        _XP_KILL_WINDOW_NAME="$(tmux display-message -p "#I")"
+        return 1
+    elif [[ "$1" =~ ^--no-attach$ ]]; then
+        _XP_OPT_ATTACH=0
+        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
+        return 1
+
+    # ----------------
+    # Other options
+    # ----------------
+    else
+        echo "Invalid option -- '${1#--}'" >&2
+        __xpanes::usage
+        echo "Try '$_XP_THIS_FILE_NAME --help' for more information." >&2
+        exit 4
+    fi
+}
+
 __xpanes::parse_options() {
 
     while (( $# > 0 ))
@@ -462,62 +573,12 @@ __xpanes::parse_options() {
                 _XP_ARGS=("${_XP_ARGS[@]}" "$1")
                 shift
             else
-                if   [[ "$1" =~ ^--help$ ]]; then
-                    __xpanes::usage
-                    __xpanes::usage_verbose
-                    exit 0
-
-                elif [[ "$1" =~ ^--version$ ]]; then
-                    __xpanes::version
-                    exit 0
-
-                elif [[ "$1" =~ ^--desync$ ]]; then
-                    _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                    _XP_OPT_IS_SYNC=0
-                    shift
-
-                elif [[ "$1" =~ ^--log-format=.*$ ]]; then
-                    _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                    _XP_OPT_LOG_STORE=1
-                    _XP_LOG_FORMAT="${1#--log-format=}"
-                    shift
-
-                elif [[ "$1" =~ ^--log ]]; then
-                    _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                    _XP_OPT_LOG_STORE=1
-                    if [[ "$1" =~ ^--log=.*$  ]]; then
-                        _XP_LOG_DIR="${1#--log=}"
-                    fi
-                    shift
-
-                elif [[ "$1" =~ ^--ssh$ ]]; then
-                    _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                    _XP_CMD_UTILITY="$_XP_SSH_CMD_UTILITY"
-                    shift
-
-                # For unit testing
-                elif [[ "$1" =~ ^--dry-run$ ]]; then
-                    _XP_OPT_DRY_RUN=1
-                    shift
-
-                elif [[ "$1" =~ ^--kill$ ]]; then
-                    _XP_KILL_WINDOW_NAME="$(tmux display-message -p "#I")"
-                    shift
-
-                elif [[ "$1" =~ ^--no-attach$ ]]; then
-                    _XP_OPT_ATTACH=0
-                    _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                    shift
-
-                # ----------------
-                # Other options
-                # ----------------
-                else
-                    echo "Invalid option -- '${1#--}'" >&2
-                    __xpanes::usage
-                    echo "Try '$_XP_THIS_FILE_NAME --help' for more information." >&2
-                    exit 4
-                fi
+                local _shift_count="0"
+                set +e
+                __xpanes::enable_long_options "$@"
+                _shift_count="$?"
+                set -e
+                [ "$_shift_count" = "1" ] && _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1") && shift
             fi
             ;;
 
@@ -529,60 +590,21 @@ __xpanes::parse_options() {
                 _XP_ARGS=("${_XP_ARGS[@]}" "$1")
                 shift
             else
-                _s_opts="[hVld]"
-                _m_opts="[ISc]"
-                if [[ "$1" =~ ^-${_s_opts}+  ]];then
-                    if   [[ "$1" =~ h ]]; then
-                        __xpanes::usage
-                        __xpanes::usage_verbose
-                        exit 0
-                    elif [[ "$1" =~ V ]]; then
-                        __xpanes::version
-                        exit 0
-                    elif [[ "$1" =~ l ]]; then
-                        _XP_OPT_LOG_STORE=1
-                    elif [[ "$1" =~ d ]]; then
-                        _XP_OPT_IS_SYNC=0
-                    fi
-                    _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                elif [[ "$1" =~ ^-${_s_opts}*I ]]; then
-                    if [[ "$1" =~ ^-${_s_opts}*I.+ ]]; then
-                        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                        _XP_REPSTR="$(echo "$1" | perl -ple "s/^-${_s_opts}*?I//")"
-                    # Behavior like this.
-                    # -IAAA         -- _XP_REPSTR="AAA"
-                    # -I AAA BBB    -- _XP_REPSTR="AAA"
-                    # -I"AAA BBB"   -- _XP_REPSTR="AAA BBB"
-                    # -IAAA BBB     -- _XP_REPSTR="AAA", _XP_ARGS=("BBB")
-                    # -I -d ...     -- _XP_REPSTR="{}"
-                    elif ! [[ "$2" =~ ^-.* ]]; then
-                        _XP_REPSTR="$2"
-                        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1" "$_XP_REPSTR")
-                        shift
-                    fi
-                    shift
 
-                elif [[ "$1" =~ ^-${_s_opts}*c ]]; then
-                    if [[ "$1" =~ ^-${_s_opts}*c.+ ]]; then
-                        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                        _XP_CMD_UTILITY="$(echo "$1" | perl -ple "s/^-${_s_opts}*?c//")"
-                    elif ! [[ "$2" =~ ^-.* ]]; then
-                        _XP_CMD_UTILITY="$2"
-                        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1" "$_XP_CMD_UTILITY")
-                        shift
-                    fi
-                    shift
-
-                elif [[ "$1" =~ ^-${_s_opts}*S ]]; then
-                    if [[ "$1" =~ ^-${_s_opts}*S.+ ]]; then
-                        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1")
-                        _XP_SOCKET_PATH="$(echo "$1" | perl -ple "s/^-${_s_opts}*?S//")"
-                    elif ! [[ "$2" =~ ^-.* ]]; then
-                        _XP_SOCKET_PATH="$2"
-                        _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1" "$_XP_SOCKET_PATH")
-                        shift
-                    fi
-                    shift
+                local _shift_count="0"
+                if [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}*${_XP_FREE_OPTIONS}  ]];then
+                    set +e
+                    __xpanes::load_free_options "$@"
+                    _shift_count="$?"
+                    set -e
+                    [ "$_shift_count" = "1" ] && _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1") && shift
+                    [ "$_shift_count" = "2" ] && _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1" "$2") && shift && shift
+                elif [[ "$1" =~ ^-${_XP_FLAG_OPTIONS}+$  ]];then
+                    set +e
+                    __xpanes::load_flag_options "$1"
+                    _shift_count="$?"
+                    set -e
+                    [ "$_shift_count" = "1" ] && _XP_OPTIONS=("${_XP_OPTIONS[@]}" "$1") && shift
 
                 # ----------------
                 # Other options
